#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Compute the logarithm of a number stream on stdin and print it to stdout

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import math
import sys


def main():
    for line in sys.stdin:
        if not line.strip():
            print(line, end='')
        value = float(line.strip())
        print(math.log(value))


if __name__ == "__main__":
    main()
