#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Compute the maximum of a number stream piped from stdin

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import sys

def main():
    maximum = None
    for line in sys.stdin:
        if not line.strip():
            continue
        val = float(line.strip())
        maximum = val if maximum is None else max(maximum ,val)
    print(maximum)


if __name__ == "__main__":
    main()
