#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Print the median of a data stream

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import argparse
import sys


def main():
    values = []
    for line in sys.stdin:
        v = line.strip()
        try:
            vv = float(v)
        except ValueError:
            print(f"Skipping invalid value: {v}", file=sys.stderr)
        values.append(vv)
    values.sort()
    n = len(values)
    i = n // 2
    if n % 2 == 1:
        median = values[i]
    else:
        median = (values[i - 1] + values[i]) / 2
    print(median)


if __name__ == "__main__":
    main()
