#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Compute the minimum of a number stream piped from stdin

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import sys

def main():
    minimum = None
    for line in sys.stdin:
        if not line.strip():
            continue
        val = float(line.strip())
        minimum = val if minimum is None else min(minimum ,val)
    print(minimum)


if __name__ == "__main__":
    main()
