#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Print the mode of a data stream

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import argparse
import sys

from collections import Counter


def main():
    values = []
    for line in sys.stdin:
        v = line.strip()
        values.append(v)
    counter = Counter(values)
    M = counter.most_common(1)[0]
    print(" ".join(map(str, M)))


if __name__ == "__main__":
    main()
