#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Compute a quantile of a number stream on stdin

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import argparse
import numpy as np
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "quantile", help="Quantile to compute", type=float, nargs="+"
    )
    return parser.parse_args()


def main():
    args = parse_args()
    values = []
    for line in sys.stdin:
        if not line.strip():
            continue
        values.append(float(line.strip()))
    for q in args.quantile:
        print(np.quantile(values, q))


if __name__ == "__main__":
    main()
