#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Round a datastream to a given number of digits.

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import argparse
import sys

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('n', help='Number of digits to round to', default=0, 
            type=int)
    return parser.parse_args()

def main():
    args = parse_args()
    for line in sys.stdin:
        if not line.strip():
            continue
        value = float(line.strip())
        r = round(value, args.n)
        print(r)

if __name__ == '__main__':
    main()

