#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Create a scatterplot of two variables

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2021, G.J.J. van den Burg

"""

import argparse
import matplotlib.pyplot as plt
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-d",
        "--delimiter",
        help="Delimiter between observations of different dimensions. Default is whitespace",
    )
    parser.add_argument(
        "-t",
        "--transpose",
        help="Transpose the data before plotting",
        action="store_true",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    sep = args.delimiter

    data = []
    for line in sys.stdin:
        if not line.strip():
            continue

        values = line.strip().split(sep)
        row = []
        for value in values:
            if value.strip():
                try:
                    v = float(value)
                except ValueError:
                    v = float("nan")
                row.append(v)
            else:
                row.append(float("nan"))
        data.append(row)

    if args.transpose:
        data = list(map(list, zip(*data)))

    for i, row in enumerate(data):
        if not len(row) == 2:
            raise ValueError(
                f"Expected two values per line, {len(row)} found on line {i}"
            )

    xs = [r[0] for r in data]
    ys = [r[1] for r in data]

    plt.scatter(xs, ys)
    plt.show()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit(1)
