#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Compute the sum of a number stream on stdin

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import sys

def main():
    total = 0.0
    for line in sys.stdin:
        if not line.strip():
            continue
        total += float(line.strip())
    print(total)


if __name__ == "__main__":
    main()
