#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Compute the sum of a number stream on stdin

Author: Gertjan van den Burg
License: See LICENSE file
Copyright (c) 2020, G.J.J. van den Burg

"""

import argparse
import sys

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--ignore', help='Ignore non-numeric values', 
            action='store_true')
    return parser.parse_args()

def main():
    args = parse_args()
    total = 0.0
    for line in sys.stdin:
        if not line.strip():
            continue
        try:
            value = float(line.strip())
        except ValueError:
            if args.ignore:
                continue
            else:
                raise
        total += value
    print(total)


if __name__ == "__main__":
    main()
